/**
 * The Worker's front door (wrangler.jsonc → main). On Workers Free a request gets 10 ms of CPU, and Next.js
 * spends 30–60 ms answering even a page it only reads from its cache, several hundred when it first starts in
 * a fresh isolate: error 1102. So what a visitor asks for over and over is answered here, from the static
 * assets, without starting Next:
 *  - a prerendered page, and the prefetch segments the router fetches for each link before it is clicked
 *    (copied out of the build by scripts/static-pages.mjs);
 *  - a prerendered file such as /icon.svg, which browsers fetch again on every page;
 *  - a page view posted to /api/track, unless the admin is signed in.
 * The responses carry the headers Next sends for the same request. Anything else, or anything here that does
 * not match exactly, goes to Next as before: OpenNext's own worker is called unchanged.
 */
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- generated by `opennextjs-cloudflare build`
import openNext from "./.open-next/worker.js"
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore -- generated by scripts/static-pages.mjs, which the wrangler build runs first
import manifest from "./.open-next/static-pages.json"
import { SESSION_COOKIE } from "./src/lib/admin-cookie"
import type { D1Database } from "./src/lib/db"
import { SECURITY_HEADERS } from "./src/lib/security-headers"
import { pageKey, segmentFile } from "./src/lib/static-route"
import { cookieValue, trackView, type Cf } from "./src/lib/track"

type Env = { ASSETS: { fetch(req: Request): Promise<Response> }; DB?: D1Database }
type Manifest = { pages: string[]; pageHeaders: Record<string, string>; files: Record<string, Record<string, string>> }

const { pages, pageHeaders, files } = manifest as Manifest
const PAGES = new Set(pages)
const VARY = "rsc, next-router-state-tree, next-router-prefetch, next-router-segment-prefetch"
const PAGE = { ...pageHeaders, "cache-control": "s-maxage=31536000", vary: VARY }
// Next sends a segment without the stale time; the router takes it from the page.
const SEGMENT = Object.fromEntries(Object.entries(PAGE).filter(([k]) => k !== "x-nextjs-stale-time"))

const worker = {
  async fetch(request: Request, env: Env, ctx: unknown): Promise<Response> {
    return (await fromAssets(request, env)) ?? (await track(request, env)) ?? openNext.fetch(request, env, ctx)
  },
}
export default worker

async function fromAssets(req: Request, env: Env): Promise<Response | null> {
  if (req.method !== "GET" && req.method !== "HEAD") return null
  const url = new URL(req.url)

  const file = Object.hasOwn(files, url.pathname) ? files[url.pathname] : undefined
  if (file) return serve(env, req, `${url.pathname}.body`, file)

  const page = pageKey(url.pathname, url.searchParams)
  if (!page || !PAGES.has(page)) return null
  if (req.headers.get("rsc") !== "1") return serve(env, req, `${page}.page`, { ...PAGE, "content-type": "text/html; charset=utf-8" })

  // A prefetch segment. A navigation, or a prefetch of the whole page, stays with Next: the router only sends
  // those when it has no segments for the page, which for these pages is rare.
  const segment = req.headers.get("next-router-segment-prefetch")
  if (req.headers.get("next-router-prefetch") !== "1" || !segment || !/^[\x20-\x7e]+$/.test(segment)) return null
  const found = await serve(env, req, `${page}.seg/${segmentFile(segment)}`, {
    ...SEGMENT,
    "content-type": "text/x-component",
    "x-nextjs-postponed": "2",
  })
  // A segment this page doesn't have: the router guessed at the page's layout. Next answers the same way.
  return (
    found ??
    withSecurity(
      new Response(null, {
        status: 404,
        headers: { "x-nextjs-postponed": "2", "cache-control": "private, no-cache, no-store, max-age=0, must-revalidate", vary: VARY },
      }),
    )
  )
}

async function serve(env: Env, req: Request, name: string, headers: Record<string, string>): Promise<Response | null> {
  const asset = await env.ASSETS.fetch(new Request(`https://assets.local/cdn-cgi/_pages${name}`)).catch(() => null)
  if (!asset) return null
  if (!asset.ok) {
    await asset.body?.cancel()
    return null
  }
  return withSecurity(new Response(req.method === "HEAD" ? null : asset.body, { status: 200, headers }))
}

function withSecurity(res: Response): Response {
  for (const [k, v] of Object.entries(SECURITY_HEADERS)) res.headers.set(k, v)
  return res
}

async function track(req: Request, env: Env): Promise<Response | null> {
  if (req.method !== "POST" || new URL(req.url).pathname !== "/api/track") return null
  // A signed-in admin's views are not counted; checking the session is Next's job.
  if (cookieValue(req, SESSION_COOKIE) !== undefined) return null
  return withSecurity(await trackView(req, { db: env.DB ?? null, cf: (req as { cf?: Cf }).cf, signedIn: async () => false }))
}
